{
    "version": "2",
    "volumes": {
        "mongo_data": {},
        "pg_data": {}
    },
    "services": {
        "postgres": {
            "image": "postgres:9.4-alpine",
            "environment": {
                "POSTGRES_USER": "postgres",
                "POSTGRES_DB": "postgres"
            },
            "volumes": [
                "pg_data:/var/lib/postgresql/data"
            ],
            "ports": [
                "5432:5432"
            ]
        },
        "mongo": {
            "image": "mongo:2.4",
            "volumes": [
                "mongo_data:/data/db"
            ],
            "ports": [
                "27017:27017"
            ]
        },
        "orientdb": {
            "image": "orientdb:2.0.18",
            "environment": {
                "ORIENTDB_ROOT_PASSWORD": "rootpwd"
            },
            "volumes": [
                "/host/path/to/orientdb_data:/orientdb/databases",
                "/host/path/to/orientdb_backup:/orientdb/backup"
            ],
            "ports": [
                "2480:2480",
                "2424:2424"
            ]
        },
        "php-fpm": {
            "restart": always,
            "build": {
                "context": "./php",
                "dockerfile": "Dockerfile"
            },
            "volumes": [
                "/host/path/to/html:/var/www/html",
                "/host/path/to/php/php.ini:/usr/local/etc/php/php.ini:ro",
                "/host/path/to/cron:/etc/cron.d/",
                "./php/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro",
                "./php/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini:ro"
            ],
            "depends_on": [
                "postgres"
            ]
        },
        "nginx": {
            "image": "nginx:1.8.1-alpine",
            "volumes": [
                "/host/path/to/html:/var/www/html",
                "/host/path/to/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            ],
            "ports": [
                "80:80"
            ],
            "depends_on": [
                "php-fpm"
            ]
        },
        "redis_db": {
            "image": "redis:3.0-alpine",
            "volumes": [
                "/host/path/to/redisdb_data:/data"
            ],
            "ports": [
                "6379:6379"
            ]
        },
        "smtp": {
            "image": "namshi/smtp",
            "restart": "always",
            "environment": {
                "RELAY_NETWORKS": ":0.0.0.0/0",
                "MAILNAME": "dhost.com"
            },
            "ports": [
                "25:25"
            ]    
        }
    }
}

